import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import ReactQueryProvider from "@/provider/ReactQueryProvider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className="flex flex-col md:flex-row">
          <SideBar />
         <div className="w-full flex items-center justify-center mt-4"><div className=""> {children}</div></div>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
